[pytest]
filterwarnings =
    ignore:.*'soft_unicode' has been renamed to 'soft_str'*:DeprecationWarning
    ignore:unclosed file .*:ResourceWarning
env_files =
    test.env
testpaths =
    tests/unit
    tests/functional
    tests/performance
markers =
    performance: marks tests as performance benchmarks
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)-8s %(name)s – %(message)s
log_cli_date_format = %H:%M:%S
